---
title: "I. Detjens: tDCS bei dystonen PianistInnen"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{I. Detjens: tDCS bei dystonen PianistInnen}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
bibliography: /home/grossbach/files/_sonstiges/000literaturdb.bib
csl: /home/grossbach/files/_sonstiges/frontiers-in-neuroscience.csl
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NULL
)
```

```{r setup}
library(detjenstDCS)
## ggplot2:
ggplot2::theme_set(ggplot2::theme_light(base_size = 10))
## knitr & kfigr:
knitr::knit_hooks$set(anchor = kfigr::hook_anchor)
knitr::opts_knit$set(kfigr.link = TRUE,
                     kfigr.prefix = TRUE)
knitr::opts_chunk$set(comment = NULL,
                      echo = FALSE,
                      fig.width = 7,
                      fig.height = 5,
                      cache = FALSE)
## rstan:
options(mc.cores = parallel::detectCores(),
        digits = 3,
        knitr.kable.NA = "")
rstan::rstan_options(auto_write = TRUE)
## Constants:
MODEL <- FALSE # Set to TRUE to run computationally costly models
DO_IT <- FALSE # Set to TRUE to run simulation models
DIAGN_PLOTS <- FALSE # Set to TRUE to show diagnostic plots
FIGREF <- "Fig." # type for pics and plots, kfigr::figr()
TABREF <- "Tab." # type for tables, kfigr::figr()
PRIORREF <- "Prior" # type for priors, kfigr::figr()
EQREF <- "Eq." # type for model equations, kfigr::figr()
SRCREF <- "Src." # type for source code blocks, kfigr::figr()
path_to_files <- "../data"
```

Fünf dystone PianistInnen (P01 -- P05) wurden im Abstand von 7 Tagen (d1, d8 und d15) mit tDC stimuliert. Vorher (prä) und nachher (post) wurde die zeitliche Regelmäßigkeit des C-Dur-Tonleiterspiels (aufwärts und abwärts) am MIDI-Klavier registriert. Nach weiteren vier Wochen wurde eine follow-up-Messung (ohne Stimulation!) erhoben (d48).

```{r}
## Extract patient codes from directories:
patient_codes <- get_patient_code(path_to_files)
relevant_fnames <- list.files(path = path_to_files, 
                              pattern = ".*\\.xlsx$", 
                              recursive = TRUE, 
                              full.names = TRUE)
unique_days <- get_day_numbers(relevant_fnames)
tm <- c("pre", "post", "")
status <- c("bearbeitet_extra_included", 
            "bearbeitet", 
            "")
# fname_components <- expand.grid(factor(patient_codes), 
#                                 factor(unique_days),
#                                 factor(status))
fnames <- get_correct_fnames(relevant_fnames,
                             patient_codes, 
                             unique_days, 
                             tm,
                             status)
n_fnames <- length(fnames)
## Read in as follows:
## ID   Day Time  Scale Ascend  IOI   Fname
## ---  --- ----  ----- ------  ----  --------------------------
## P03  1   pre   1     1       107   P03_d1_pre_bearbeitet.xlsx
##
midi_data <- data.frame(ID = character(0),
                        Day = character(0),
                        Time = character(0),
                        Scale = integer(0),
                        Ascend = integer(0),
                        IOI = numeric(0),
                        Fname = character(0))
for (fn in 1:n_fnames) {
  tab <- readxl::read_xlsx(list.files(path = path_to_files, 
                                      pattern = fnames[fn], 
                                      full.names = TRUE, recursive = TRUE))
}
```


